name: Python CI v7

on:
  push:
  pull_request:

permissions:
  contents: read
  security-events: write

jobs:
  ci:
    uses: PJawanth/.github/.github/workflows/Python_ci_template.yml@v4
    with:
      python_versions: "3.10,3.11,3.12"
      run_tests: true
      enable_security: true
      coverage_threshold: 80
      debug: true
